stages:
  - publish

variables:
  DOCKER_HUB_REGISTRY_IMAGE: pockost/proftpd
  DOCKERFILE: Dockerfile
  CONTEXT: "."
  TAG_SUFFIX: ""

.only-tag:
  rules:
    - if: $CI_COMMIT_TAG =~ /^\d+\.\d+/

.build:
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    - wget https://github.com/jqlang/jq/releases/download/jq-1.7.1/jq-linux-amd64  -O /bin/jq
    - chmod +x /bin/jq
    - mkdir -p /kaniko/.docker ~/.docker/
    - test -f ~/.docker/config.json || echo '{}' > ~/.docker/config.json
    - cat ~/.docker/config.json | /bin/jq  ".auths |= . + {\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}" > /kaniko/.docker/config.json
  script:
    - /kaniko/executor
      --context ${CONTEXT}
      --dockerfile ${DOCKERFILE}
      --destination ${DOCKER_HUB_REGISTRY_IMAGE}:${TAG_SUFFIX}${CI_COMMIT_TAG}
      --force


build:base:
  extends:
    - .build
    - .only-tag
  variables:
    CONTEXT: "base/"

